// <auto-generated />
using System;
using Magazine_ASP.MVC.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Magazine_ASP.MVC.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Magazine_ASP.MVC.DAL.Entities.ImageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "img/news-350x223-1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "img/news-350x223-2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "img/news-350x223-3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "img/news-350x223-4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "img/news-350x223-5.jpg"
                        });
                });

            modelBuilder.Entity("Magazine_ASP.MVC.DAL.Entities.NewsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<int>("Tag")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 1, 29, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(389),
                            ImageId = 2,
                            Tag = 1,
                            Title = "#1 Title",
                            ViewsCount = 163
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 1, 27, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(475),
                            ImageId = 3,
                            Tag = 1,
                            Title = "#2 Title",
                            ViewsCount = 357
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 1, 27, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(481),
                            ImageId = 4,
                            Tag = 4,
                            Title = "#3 Title",
                            ViewsCount = 112
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2022, 1, 27, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(485),
                            ImageId = 5,
                            Tag = 2,
                            Title = "#4 Title",
                            ViewsCount = 762
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2022, 1, 26, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(488),
                            ImageId = 1,
                            Tag = 3,
                            Title = "#5 Title",
                            ViewsCount = 436
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2022, 1, 26, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(493),
                            ImageId = 2,
                            Tag = 2,
                            Title = "#6 Title",
                            ViewsCount = 123
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2022, 1, 25, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(497),
                            ImageId = 3,
                            Tag = 1,
                            Title = "#7 Title",
                            ViewsCount = 422
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2022, 1, 29, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(501),
                            ImageId = 4,
                            Tag = 1,
                            Title = "#8 Title",
                            ViewsCount = 447
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2022, 1, 25, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(504),
                            ImageId = 5,
                            Tag = 2,
                            Title = "#9 Title",
                            ViewsCount = 751
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2022, 1, 29, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(509),
                            ImageId = 1,
                            Tag = 4,
                            Title = "#10 Title",
                            ViewsCount = 563
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2022, 1, 26, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(513),
                            ImageId = 2,
                            Tag = 2,
                            Title = "#11 Title",
                            ViewsCount = 868
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2022, 1, 27, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(517),
                            ImageId = 3,
                            Tag = 3,
                            Title = "#12 Title",
                            ViewsCount = 165
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2022, 1, 28, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(521),
                            ImageId = 4,
                            Tag = 2,
                            Title = "#13 Title",
                            ViewsCount = 275
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2022, 1, 26, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(524),
                            ImageId = 5,
                            Tag = 2,
                            Title = "#14 Title",
                            ViewsCount = 152
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2022, 1, 29, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(528),
                            ImageId = 1,
                            Tag = 1,
                            Title = "#15 Title",
                            ViewsCount = 692
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2022, 1, 26, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(532),
                            ImageId = 2,
                            Tag = 4,
                            Title = "#16 Title",
                            ViewsCount = 265
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2022, 1, 29, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(535),
                            ImageId = 3,
                            Tag = 3,
                            Title = "#17 Title",
                            ViewsCount = 559
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2022, 1, 29, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(540),
                            ImageId = 4,
                            Tag = 4,
                            Title = "#18 Title",
                            ViewsCount = 397
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2022, 1, 28, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(543),
                            ImageId = 5,
                            Tag = 3,
                            Title = "#19 Title",
                            ViewsCount = 334
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2022, 1, 26, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(554),
                            ImageId = 1,
                            Tag = 4,
                            Title = "#20 Title",
                            ViewsCount = 900
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2022, 1, 26, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(558),
                            ImageId = 2,
                            Tag = 1,
                            Title = "#21 Title",
                            ViewsCount = 405
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2022, 1, 25, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(561),
                            ImageId = 3,
                            Tag = 2,
                            Title = "#22 Title",
                            ViewsCount = 848
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2022, 1, 29, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(565),
                            ImageId = 4,
                            Tag = 1,
                            Title = "#23 Title",
                            ViewsCount = 301
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2022, 1, 26, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(569),
                            ImageId = 5,
                            Tag = 1,
                            Title = "#24 Title",
                            ViewsCount = 134
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2022, 1, 28, 14, 56, 37, 554, DateTimeKind.Local).AddTicks(573),
                            ImageId = 1,
                            Tag = 4,
                            Title = "#25 Title",
                            ViewsCount = 813
                        });
                });

            modelBuilder.Entity("Magazine_ASP.MVC.DAL.Entities.NewsEntity", b =>
                {
                    b.HasOne("Magazine_ASP.MVC.DAL.Entities.ImageEntity", "ImageItem")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("ImageItem");
                });
#pragma warning restore 612, 618
        }
    }
}
